# --- COMA specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True


runner: "parallel"

buffer_size: 10
batch_size_run: 10
batch_size: 10

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0003

obs_agent_id: True
obs_last_action: True
obs_individual_obs: False


# use COMA
mac: "non_shared_mac"
agent: "rnn_ns"
standardise_returns: True
standardise_rewards: True
use_rnn: True
agent_output_type: "pi_logits"
learner: "coma_learner"
critic_q_fn: "coma"
critic_baseline_fn: "coma"
critic_train_mode: "seq"
critic_train_reps: 1
entropy_coef: 0.005
q_nstep: 72  # 0 corresponds to default Q, 1 is r + gamma*Q, etc
critic_type: coma_critic_ns

name: "coma_ns"
# t_max: 20050000
