# --- ICQ specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .05
epsilon_anneal_time: 5000
mask_before_softmax: True

#runner: "episode"
runner: "parallel"

buffer_size: 2500
batch_size_run: 16 # 10
batch_size: 16

env_args:
  state_last_action: True # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 14400

lr: 0.0005
critic_lr: 0.0001
weight_decay: 0.0
td_lambda: 0.93

standardise_rewards: True
standardise_returns: True

# use qmix
mixing_embed_dim: 64
hypernet_layers: 2
hypernet_embed: 64

critic_hidden_dim: 64
optim_type: "rmsprop"
icq_alpha: 0.1
icq_beta: 1000
use_rnn: True

# use COMA
agent_output_type: "pi_logits"
learner: "icq_learner"
q_nstep: 72  # 0 corresponds to default Q, 1 is r + gamma*Q, etc

name: "icq"
