# --- IPPO (Independent Rewards) specific parameters ---
use_local_rewards: False

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 4
batch_size_run: 4
batch_size: 4

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

lr: 0.0003

obs_agent_id: False
obs_last_action: True
obs_individual_obs: False

# use IA2C
mac: "non_shared_mac"
agent: "rnn_ns"
agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.005
standardise_returns: True
standardise_rewards: True
use_rnn: True
q_nstep: 72 # 1 corresponds to normal r + gammaV
critic_type: "ac_critic"
epochs: 2
eps_clip: 0.2

name: "ippo_ir_ns"

# t_max: 20050000
