# --- IPPO NS specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 4
batch_size_run: 4
batch_size: 4

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0003

obs_agent_id: True
obs_last_action: True
obs_individual_obs: False

mac: "non_shared_mac"
agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.005
standardise_returns: True
standardise_rewards: True
use_rnn: True
epochs: 2
eps_clip: 0.2
q_nstep: 72 # 1 corresponds to normal r + gammaV
critic_type: "ac_critic_ns"
name: "ippo_local_ns"

agent: "explicit_comm_ns"
comm: False
use_local_rewards: True
