# --- Central-V specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

buffer_size: 10
runner: "parallel"
batch_size_run: 4
batch_size: 10

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0003

obs_agent_id: True
obs_last_action: True
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "actor_critic_learner"
entropy_coef: 0.005
use_rnn: True
standardise_returns: True
standardise_rewards: True
q_nstep: 72 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"

name: "maa2c"
