# --- MADDPG  NSspecific parameters ---

runner: "episode"

buffer_size: 10000
# update the target network every {} episodes
target_update_interval_or_tau: 0.01

obs_agent_id: True
obs_last_action: True
obs_individual_obs: False


# use the maddpg_learner to train
agent: "rnn_ns"
mac: "maddpg_mac"
reg: 0.001
batch_size: 16
lr: 0.0003
standardise_returns: True
standardise_rewards: True
use_rnn: True
learner: "maddpg_learner"
agent_output_type: "pi_logits"
hidden_dim: 64
critic_type: "maddpg_critic_ns"
name: "maddpg_ns"
