# --- MADDPG specific parameters ---

runner: "parallel"
batch_size_run: 4

buffer_size: 1000
# update the target network every {} episodes
target_update_interval_or_tau: 200

obs_agent_id: True
obs_last_action: True
obs_individual_obs: False

# use the madddpg_learner to train
mac: "maddpg_mac"
reg: 0.001
batch_size: 32
lr: 0.0003
use_rnn: True

standardise_returns: True
standardise_rewards: True

learner: "maddpg_learner"
agent_output_type: "pi_logits"
# hidden_dim: 64
critic_type: "maddpg_critic"
name: "maddpg"
