# --- MAPPO_NS specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 4
batch_size_run: 4
batch_size: 4

# update the target network every {} training steps
target_update_interval_or_tau: 200

lr: 0.0003

obs_agent_id: True
obs_last_action: True
obs_individual_obs: False

mac: "non_shared_mac"
agent: "rnn_ns"
agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.005
use_rnn: True
standardise_returns: True
standardise_rewards: True
q_nstep: 72 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic_ns"
epochs: 2
eps_clip: 0.2
name: "mappo_ns"

# t_max: 20050000
