# --- MAPPO specific parameters ---

action_selector: "soft_policies"
mask_before_softmax: True

runner: "parallel"

buffer_size: 40
batch_size_run: 4
batch_size: 4

# update the target network every {} training steps
target_update_interval_or_tau: 0.01

hidden_dim: 64
lr: 0.0003

obs_agent_id: True
obs_last_action: True
obs_individual_obs: False

agent_output_type: "pi_logits"
learner: "ppo_learner"
entropy_coef: 0.001
use_rnn: True
standardise_returns: True
standardise_rewards: True
q_nstep: 72 # 1 corresponds to normal r + gammaV
critic_type: "cv_critic"
eps_clip: 0.2
epochs: 4

name: "mappo"
agent: "rnn"
comm: False
use_local_rewards: False
