# --- MATD3+BC specific parameters ---

runner: "episode"

buffer_size: 50000
target_update_interval_or_tau: .005

obs_agent_id: True
obs_last_action: True
obs_individual_obs: True

critic_individual_obs: True
critic_last_action: True
critic_agent_id: True

hidden_dim: 128

mac: "maddpg_mac"
batch_size: 32
lr: 0.001
use_rnn: True

standardise_returns: False
standardise_rewards: True

learner: "matd3_learner"
agent_output_type: "pi_logits"

critic_type: "maddpg_critic"
optim_type: "adam"
actor_freq: 2
td3_alpha: 1.0
bc_lambda: 0.1

name: "matd3_bc"
use_local_rewards: True
importance_sampling: False