env: tsc

env_args:
  scenario: manhattan_28_7
  simulator_backend: "cityflow"
  map_name: manhattan_28_7
  misc:
    reward_gamma: 0.0
  cityflow:
    seed: 42
    save_replay: False
    episode_limit: 360
    flow_rate_type: random
    flow_files: [
      "randomized/high/0__manhattan_28_7__gaussian_flows.json",
      "randomized/high/1__manhattan_28_7__gaussian_flows.json",
      "randomized/high/2__manhattan_28_7__gaussian_flows.json",
      "randomized/high/3__manhattan_28_7__gaussian_flows.json",
      "randomized/high/4__manhattan_28_7__gaussian_flows.json",
      "randomized/high/5__manhattan_28_7__gaussian_flows.json",
      "randomized/high/6__manhattan_28_7__gaussian_flows.json",
      "randomized/high/7__manhattan_28_7__gaussian_flows.json",
      "randomized/high/8__manhattan_28_7__gaussian_flows.json",
      "randomized/high/9__manhattan_28_7__gaussian_flows.json",
      "randomized/high/10__manhattan_28_7__gaussian_flows.json",
      "randomized/high/11__manhattan_28_7__gaussian_flows.json",
      "randomized/high/12__manhattan_28_7__gaussian_flows.json",
      "randomized/high/13__manhattan_28_7__gaussian_flows.json",
      "randomized/high/14__manhattan_28_7__gaussian_flows.json",
      "randomized/high/15__manhattan_28_7__gaussian_flows.json",
      "randomized/high/16__manhattan_28_7__gaussian_flows.json",
      "randomized/high/17__manhattan_28_7__gaussian_flows.json",
      "randomized/high/18__manhattan_28_7__gaussian_flows.json",
      "randomized/high/19__manhattan_28_7__gaussian_flows.json",
      "randomized/high/20__manhattan_28_7__gaussian_flows.json",
      "randomized/high/21__manhattan_28_7__gaussian_flows.json",
      "randomized/high/22__manhattan_28_7__gaussian_flows.json",
      "randomized/high/23__manhattan_28_7__gaussian_flows.json",
      "randomized/high/24__manhattan_28_7__gaussian_flows.json",
      "randomized/high/25__manhattan_28_7__gaussian_flows.json",
      "randomized/high/26__manhattan_28_7__gaussian_flows.json",
      "randomized/high/27__manhattan_28_7__gaussian_flows.json",
      "randomized/high/28__manhattan_28_7__gaussian_flows.json",
      "randomized/high/29__manhattan_28_7__gaussian_flows.json",
      "randomized/high/30__manhattan_28_7__gaussian_flows.json",
      "randomized/high/31__manhattan_28_7__gaussian_flows.json",
      "randomized/high/32__manhattan_28_7__gaussian_flows.json",
      "randomized/high/33__manhattan_28_7__gaussian_flows.json",
      "randomized/high/34__manhattan_28_7__gaussian_flows.json",
      "randomized/high/35__manhattan_28_7__gaussian_flows.json",
      "randomized/high/36__manhattan_28_7__gaussian_flows.json",
      "randomized/high/37__manhattan_28_7__gaussian_flows.json",
      "randomized/high/38__manhattan_28_7__gaussian_flows.json",
      "randomized/high/39__manhattan_28_7__gaussian_flows.json",
      "randomized/high/40__manhattan_28_7__gaussian_flows.json",
      "randomized/high/41__manhattan_28_7__gaussian_flows.json",
      "randomized/high/42__manhattan_28_7__gaussian_flows.json",
      "randomized/high/43__manhattan_28_7__gaussian_flows.json",
      "randomized/high/44__manhattan_28_7__gaussian_flows.json",
      "randomized/high/45__manhattan_28_7__gaussian_flows.json",
      "randomized/high/46__manhattan_28_7__gaussian_flows.json",
      "randomized/high/47__manhattan_28_7__gaussian_flows.json",
      "randomized/high/48__manhattan_28_7__gaussian_flows.json",
      "randomized/high/49__manhattan_28_7__gaussian_flows.json",
      "randomized/high/50__manhattan_28_7__gaussian_flows.json",
      "randomized/high/51__manhattan_28_7__gaussian_flows.json",
      "randomized/high/52__manhattan_28_7__gaussian_flows.json",
      "randomized/high/53__manhattan_28_7__gaussian_flows.json",
      "randomized/high/54__manhattan_28_7__gaussian_flows.json",
      "randomized/high/55__manhattan_28_7__gaussian_flows.json",
      "randomized/high/56__manhattan_28_7__gaussian_flows.json",
      "randomized/high/57__manhattan_28_7__gaussian_flows.json",
      "randomized/high/58__manhattan_28_7__gaussian_flows.json",
      "randomized/high/59__manhattan_28_7__gaussian_flows.json",
      "randomized/high/60__manhattan_28_7__gaussian_flows.json",
      "randomized/high/61__manhattan_28_7__gaussian_flows.json",
      "randomized/high/62__manhattan_28_7__gaussian_flows.json",
      "randomized/high/63__manhattan_28_7__gaussian_flows.json",
      "randomized/high/64__manhattan_28_7__gaussian_flows.json",
      "randomized/high/65__manhattan_28_7__gaussian_flows.json",
      "randomized/high/66__manhattan_28_7__gaussian_flows.json",
      "randomized/high/67__manhattan_28_7__gaussian_flows.json",
      "randomized/high/68__manhattan_28_7__gaussian_flows.json",
      "randomized/high/69__manhattan_28_7__gaussian_flows.json",
      "randomized/high/70__manhattan_28_7__gaussian_flows.json",
      "randomized/high/71__manhattan_28_7__gaussian_flows.json",
      "randomized/high/72__manhattan_28_7__gaussian_flows.json",
      "randomized/high/73__manhattan_28_7__gaussian_flows.json",
      "randomized/high/74__manhattan_28_7__gaussian_flows.json",
      "randomized/high/75__manhattan_28_7__gaussian_flows.json",
      "randomized/high/76__manhattan_28_7__gaussian_flows.json",
      "randomized/high/77__manhattan_28_7__gaussian_flows.json",
      "randomized/high/78__manhattan_28_7__gaussian_flows.json",
      "randomized/high/79__manhattan_28_7__gaussian_flows.json",
      "randomized/high/80__manhattan_28_7__gaussian_flows.json",
      "randomized/high/81__manhattan_28_7__gaussian_flows.json",
      "randomized/high/82__manhattan_28_7__gaussian_flows.json",
      "randomized/high/83__manhattan_28_7__gaussian_flows.json",
      "randomized/high/84__manhattan_28_7__gaussian_flows.json",
      "randomized/high/85__manhattan_28_7__gaussian_flows.json",
      "randomized/high/86__manhattan_28_7__gaussian_flows.json",
      "randomized/high/87__manhattan_28_7__gaussian_flows.json",
      "randomized/high/88__manhattan_28_7__gaussian_flows.json",
      "randomized/high/89__manhattan_28_7__gaussian_flows.json",
      "randomized/high/90__manhattan_28_7__gaussian_flows.json",
      "randomized/high/91__manhattan_28_7__gaussian_flows.json",
      "randomized/high/92__manhattan_28_7__gaussian_flows.json",
      "randomized/high/93__manhattan_28_7__gaussian_flows.json",
      "randomized/high/94__manhattan_28_7__gaussian_flows.json",
      "randomized/high/95__manhattan_28_7__gaussian_flows.json",
      "randomized/high/96__manhattan_28_7__gaussian_flows.json",
      "randomized/high/97__manhattan_28_7__gaussian_flows.json",
      "randomized/high/98__manhattan_28_7__gaussian_flows.json",
      "randomized/high/99__manhattan_28_7__gaussian_flows.json",
    ]
  signal:
    observation_space: lane_features
    visibility: 10
  network:
    control_scheme: decentralized

test_greedy: True
test_nepisode: 10  # (10 episodes = 1 simulation hour, 1 pymarl step = 5 sim seconds, 1 episode = 72 pymarl steps)
test_interval: 14400  # after 200 episodes
log_interval: 1440  # after 20 episodes
runner_log_interval: 1440
learner_log_interval: 1440
save_model: True
save_model_interval: 288000

t_max: 5400000  # (50000 episodes = 5000 sim hours)

use_cuda: True
use_tensorboard: True

# offline_data_folder: "jinan_3_4_results/collected_data"
offline_batch_size: 128
offline_data_folder: ""
offline_bottom_data_path: "high_manhattan_28_7_results/collected_data"
offline_data_quality: ["fixed_time", "greedy", "max_pressure", "sotl", "random", "expert"]
offline_max_buffer_size: 6000
offline_data_shuffle: True
offline_data_type: "h5"